### ISSUE TITLE
Walking Backwards

### ISSUE THREAD

**Issue by Peach774** [Parker8283/IguanaTweaks#18] opened 2014-08-10 04:32 UTC
I turned off everything but the no sleeping in beds thing and it worked except now I walk really sloww when i walk backwards.

**Comment by Parker8283** [comment] 2015-04-14 23:41
Since I'm still unable to reproduce this, I'm closing this. If someone can reproduce this with JUST Iguana Tweaks, please open a new issue and pastebin you main.cfg file and please have steps to reproduce.

**Closed by Parker8283** 2015-04-14 23:41 UTC
